---
title: "Comparing DRR and PCA"
author: "Guido Kraemer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{Compare DRR and PCA}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---

compare rotation to instrumental variables pca and canonical
correspondence analysis:


```{r, }
library(dimRed)
library(ade4)

indata <- loadDataSet("Swiss Roll", n = 500)
indata <- indata[sample(nrow(indata)),]
meth <- c('pca', 'tsne', 'drr', 'isomap')
emb <- lapply(meth, function(x) embed(indata, x, knn = 4))
names(emb) <- meth
```

```{r, result = 'hold', out.width = '45%', fig.width = 5, fig.height = 5}
lapply(emb, plot, type = '2vars')
```

```{r, }

dudis <- lapply(emb, function(x)
    as.dudi(as.data.frame(x@data@data),
            col.w = rep(1, ncol(x@data@data)),
            row.w = rep(1, nrow(x@data@data)),
            scannf = FALSE,
            nf = 2, call = NULL, type = "dudi.emb"))

names(dudis)

pcaivs <- pcaivorthos <- pcaivs.meta <- pcaivorthos.meta <- list()
for(n in meth) {
    pcaivs[[n]]           <- pcaiv(     dudis[[n]], emb[[n]]@org.data,  scannf = FALSE)
    pcaivs.meta[[n]]      <- pcaiv(     dudis[[n]], emb[[n]]@data@meta, scannf = FALSE)
    pcaivorthos[[n]]      <- pcaivortho(dudis[[n]], emb[[n]]@org.data,  scannf = FALSE)
    pcaivorthos.meta[[n]] <- pcaivortho(dudis[[n]], emb[[n]]@data@meta, scannf = FALSE)
}
```

```{r, fig.width = 7, fig.height = 7}
## pcaivs$drr
## pcaivs$pca
## pcaivs$tsne
## pcaivs$isomap

## pcaivorthos$drr
## pcaivorthos$pca
## pcaivorthos$tsne
## pcaivorthos$isomap

## dev.new()
## plot( pcaivs$isomap )
## plot( pcaivs$isomap$X )
## plot( pcaivs$isomap$Y , col = "red")
## plot( pcaivs$isomap$tab )
## plot( pcaivs$isomap$ls )
## plot( pcaivs$isomap$li )
## plot( pcaivs$isomap$l1 )
## ( pcaivs$isomap$c1 )
## ( pcaivs$isomap$fa)
## pcaiv
## pcaivs$isomap
## pcaivs$isomap$c1
## pcaivs$isomap$as
## pcaivs$isomap$co
## pcaivs$pca$cor

## class(pcaivs$isomap)
## summary(pcaivs$pca)
## summary(pcaivs$isomap)


## all(as.matrix(pcaivs$drr$Y) %*% as.matrix(pcaivs$drr$c1) ==
##     pcaivs$drr$ls)

## t(as.matrix(pcaivs$pca$X)) %*% as.matrix(pcaivs$pca$l1)
## print(t(as.matrix(pcaivs$isomap$c1)) %*% as.matrix(pcaivs$isomap$c1),digits = 20)
## max(abs(as.matrix(cbind(1, pcaivs$pca$X)) %*% as.matrix(pcaivs$pca$fa) - pcaivs$pca$li))
## max(abs(as.matrix(pcaivs$pca$tab) - pcaivs$pca$li))



## head(pcaivs$pca$X)

## plot(as.matrix(pcaivs$drr$X) %*% as.matrix(pcaivs$drr$c1))



## plot(indata)
# lapply(pcaivs, function(x) plot(x$X)) # the original data
## lapply(emb, function(x) plot(x, type = "2vars"))

## lapply(pcaivs, function(x) {
##     ## plot(x$Y,   main = 'Y')   # embedded data
##     ## plot(x$tab, main = 'tab') # projected variables
##     ## plot(x$ls,  main = 'ls')  # projection of lines of dudi$tab on ppa
##     plot(x$li,  main = 'li')  # ls predicted by X
##     ## plot(x$l1,  main = 'l1')  # pcp constraint principal components (same as li
## })

for(i in meth) {
    plot(emb[[i]], type = "2vars")
    plot(pcaivs[[i]], main = i)
    plot(pcaivs[[i]]$li, main = paste(i, "li"))
    plot(pcaivs.meta[[i]], main = paste("meta", i))
    plot(pcaivs.meta[[i]]$li, main = paste(i, "li meta"))
}

## lapply(pcaivs, plot)
## lapply(pcaivs, print)
## lapply(pcaivs, summary)

## lapply(pcaivs, function(x) x$eig)
## lapply(pcaivs, function(x) x$eig / sum(x$eig))

summary(pcaivs$drr)
summary(pcaivs.meta$drr)
summary(pcaivorthos$drr)
summary(pcaivorthos.meta$drr)

summary(pcaivs$pca)
summary(pcaivs.meta$pca)
summary(pcaivorthos$pca)
summary(pcaivorthos.meta$pca)

summary(pcaivs$tsne)
summary(pcaivs.meta$tsne)
summary(pcaivorthos$tsne)
summary(pcaivorthos.meta$tsne)

summary(pcaivs$isomap)
summary(pcaivs.meta$isomap)
summary(pcaivorthos$isomap)
summary(pcaivorthos.meta$isomap)

plot(pcaivs.meta$isomap, plabels = list(cex = 0))
dev.new()
plot(pcaivs.meta$isomap$li)
plot(pcaivs.meta$isomap$Y)
plot(pcaivs.meta$isomap$tab)
plot(new('dimRedData', data = as.matrix(pcaivs.meta$tsne$li), meta = indata@meta), type = '2vars')
plot(new('dimRedData', data = as.matrix(indata@meta),         meta = indata@meta), type = '2vars')
plot(emb$isomap)

plot(rbind(pcaivs.meta$isomap$Y,
           pcaivs.meta$isomap$tab), type = 'n')

plot(NA, xlim = c(-60, 60), ylim = c(-60, 60))
arrows(x1 = -pcaivs.meta$isomap$Y[,1],
       y1 = -pcaivs.meta$isomap$Y[,2],
       x0 = -pcaivs.meta$isomap$tab[,1],
       y0 = -pcaivs.meta$isomap$tab[,2])

```

```{r, fig.width = 7, fig.height = 7, out.width = "95%"}
library(ggplot2)
library(dimRed)
library(ade4)
library(vegan)
irisc <- as.data.frame(scale(iris[,1:4]))
iris12dudi <- as.dudi(irisc[,1:2], col.w = rep(1,2), row.w = rep(1,150), scannf = FALSE, nf = 2, call = NULL, type = "dudi.I")

biplot(dudi.pca(iris[,1:4], scannf = FALSE))

plot(irisc[,1:2])
plot(new("dimRedData", data = as.matrix(irisc[,1:2]), meta = irisc[,3:4]), type = "2vars")
plot(iris12dudi$tab)
biplot(iris12dudi)
irispcaiv <- pcaiv(iris12dudi, irisc[,3:4], scannf = FALSE, nf = 2)
plot(irispcaiv)

## ggplot(irisc,                      aes(x = Sepal.Length, y = Sepal.Width, color = Petal.Width))  + geom_point()
## ggplot(irisc,                      aes(x = Sepal.Length, y = Sepal.Width, color = Petal.Length)) + geom_point()
## ggplot(cbind(irispcaiv$ls, irisc), aes(x = Axis1,        y = Axis2,       color = Petal.Width))  + geom_point()
## ggplot(cbind(irispcaiv$ls, irisc), aes(x = Axis1,        y = Axis2,       color = Petal.Length)) + geom_point()
## ggplot(cbind(irispcaiv$l1, irisc), aes(x = RS1,          y = RS2,         color = Petal.Width))  + geom_point()
## ggplot(cbind(irispcaiv$l1, irisc), aes(x = RS1,          y = RS2,         color = Petal.Length)) + geom_point()
## ggplot(cbind(irispcaiv$li, irisc), aes(x = Axis1,        y = Axis2,       color = Petal.Length)) + geom_point()
## ggplot(cbind(irispcaiv$li, irisc), aes(x = Axis1,        y = Axis2,       color = Petal.Width))  + geom_point()

irismax <- dimRed:::.maximize_correlation(irisc[,1:2], irisc[,3:4])

irisccora <- CCorA(irisc[,3:4], irisc[,1:2])
plot(irisccora$Cx)
plot(envfit(irisccora$Cx, irisc[,3:4]))

## plot(irisccora$Cy)
## plot(envfit(irisccora$Cy, irisc[,1:2]))

## plot(as.matrix(irisc[,1:2]) %*% as.matrix(irisccora$corr.X.Cy))
## plot(envfit(as.matrix(irisc[,1:2]) %*% as.matrix(irisccora$corr.X.Cy), irisc[,3:4]))


plot(irismax$rotated)
plot(envfit(irismax$rotated, irisc[,3:4]))

plot(irisc[,1:2])
plot(envfit(irisc[,1:2], irisc[,3:4]))

plot(irispcaiv$ls)
plot(envfit(irispcaiv$ls, irisc[,3:4]))

plot(irispcaiv$l1)
plot(envfit(irispcaiv$l1, irisc[,3:4]))

plot(irispcaiv$li)
plot(envfit(irispcaiv$li, irisc[,3:4]))


```
