# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BNET_FORCE_NNMF_TESTS: 0
  BNET_FORCE_AUTOENCODER_TESTS: 0
  BNET_FORCE_UMAP_TESTS: 0
  # _R_CHECK_FORCE_SUGGESTS_: false
  # _R_CHECK_INSTALL_DEPENDS_: true
  MAKEFLAGS: "-j 2"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        r-version: [4.0, 4.1.2, 4.2]
        depends-only: [true, false]
        suggests-only: [true, false]
    env:
      _R_CHECK_DEPENDS_ONLY_: ${{ matrix.depends-only }}
      _R_CHECK_SUGGESTS_ONLY_: ${{ matrix.suggests-only }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install System libraries
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y coinor-libclp-dev mesa-common-dev libglu1-mesa-dev python3 python3-pip python3-setuptools texlive texlive-latex-extra python3-pip
        shell: sh {0}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            any::rcmdcheck
      # - name: Install dependencies
      #   run: |
      #     # reticulate::install_miniconda()
      #     # reticulate::py_install("umap-learn==0.4")
      #     # tensorflow::install_tensorflow()
      #     # keras::install_keras()
      #   shell: Rscript {0}
      - uses: r-lib/actions/check-r-package@v2
